services:
  bot:
    build: .
    image: femverify-bot:latest
    container_name: femverify-bot
    restart: unless-stopped
    tty: true
    volumes:
      - ./config.json:/app/config.json:ro
      - ./data:/app/data
